build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: postgres
  environment:
      - DATABASE_ADAPTER=postgresql
      - DATABASE_USERNAME=postgres
      - PGUSER=ci
      - PGPASSWORD=ci
      - PGHOST={{ .Containers.IP "db" }}
      - ENCRYPTION_KEY=abcdefghijklmn
      - DATABASE_URL=postgres://ci:ci@{{ .Containers.IP "db" }}:5432/travis_ci_test
  dependencies:
      containers:
        db:
          image: postgres:9.4
          environment:
            - POSTGRES_PASSWORD=ci
            - POSTGRES_USER=ci
            - POSTGRES_DB=travis_ci_test
          port_check:
            port: 5432
            timeout: 45
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: mysql
  environment:
      - DATABASE_ADAPTER=mysql2
      - MYSQL_HOST={{ .Containers.IP "db" }}
      - DATABASE_URL=mysql2://root:ci@{{ .Containers.IP "db" }}:3306/travis_ci_test
  dependencies:
      containers:
        db:
          image: mysql/mysql-server:latest
          port_check:
            port: 3306
            timeout: 45
  
ci:
  builds:
  - build_target: postgres
    name: postgres
  - build_target: mysql
    name: mysql
dependencies:
  build:
  - ruby:2.6.0
